version: 2
updates:
    - package-ecosystem: github-actions
      commit-message:
          include: scope
          prefix: ci
      directory: /
      open-pull-requests-limit: 20
      schedule:
          interval: monthly

    - package-ecosystem: npm
      commit-message:
          include: scope
          prefix: build
      cooldown:
          include: ["*"]
          semver-major-days: 60
          semver-minor-days: 21
          semver-patch-days: 7
      directory: /
      groups:
          commitlint:
              patterns:
                  - "@commitlint*"
          eslint:
              patterns:
                  - "@eslint*"
                  - "*eslint-config*"
                  - "eslint*"
      open-pull-requests-limit: 20
      schedule:
          interval: monthly
