language: node_js

cache: yarn

git:
    quiet: true

node_js:
    - '10'
    - '12'
    - '14'

# os
dist: focal

os:
    - windows

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script:
    - echo "Running tests against $(node -v)..."
    - yarn test

jobs:
    include:
        - stage: test
          name: linux deployment
          node_js: lts/*
          os: linux
          script:
              - sudo apt-get update
              - sudo apt-get -y install unrtf
              - yarn test
        - stage: test
          name: produce coverage
          node_js: lts/*
          os: windows
          script:
              - jest --coverage
              - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
              - rm -rf ./coverage
